### ISSUE TITLE
Dark Mode Icons

### ISSUE THREAD

**Issue by WildByDesign** [ozone10/7zip-Dark7zip#2]
I made these icons a few months ago.

![7zip-moderndark2](https://github.com/user-attachments/assets/2baee814-c1ef-4e84-9c1f-aabe04bf456c)

~~[7zFM.exe.res.zip](https://github.com/user-attachments/files/16215322/7zFM.exe.res.zip)~~

They are stuffed into a resource hacker res file here because I know for a fact that these are my completed ones. I have my SVG sources too but I did many variations and my SVG source folders are a complete unorganized mess right now.

Anyway, you can feel free to use these if you want. You may have to just use resource hacker to extract them for now.

**EDIT:**

There are also some more modern variants of the 7-Zip logo/icons that look a bit slicker compared to the official ones.
Link: https://sourceforge.net/p/sevenzip/discussion/45797/thread/6387e30f28/

**EDIT2:**
remove non-toolbar icons
[7zFM.exe.res.zip](https://github.com/user-attachments/files/16238518/7zFM.exe.res.zip)

**Comment by ozone10** [comment]
@WildByDesign 
looks great.
Could you adapt it for https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer.
Here is example for folder structure https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/releases/download/v2.2.1/Themes_added_on_2022-05-14.7z
IMHO most users are using this tool.

**Comment by WildByDesign** [comment]
Thank you. I have adapted it for 7-Zip Theme Changer:

[Windows 11 (win32-darkmode).zip](https://github.com/user-attachments/files/16247470/Windows.11.win32-darkmode.zip)

The only problem is that there is not much purpose to share it right now (with 7-Zip Theme Changer community) because it will only appear well for users either using your build of 7-Zip or using dark mode msstyles like Rectify11.

BTW, that parent directory up button icon, is there any way for you to hook that (`comctl32.dll`) to change it?
Or possibly just tell it to load a different icon?

Example:
![7zip-moderndark](https://github.com/user-attachments/assets/d2166c85-f00e-4763-bbd4-3ea15f81e217)

I had used a Windhawk Mod (Resource Redirect) which allowed me to hook `comctl32.dll` and replace the bitmap in memory.

**Comment by ozone10** [comment]
>The only problem is that there is not much purpose to share it right now (with 7-Zip Theme Changer community) because it will only appear well for users either using your build of 7-Zip or using dark mode msstyles like Rectify11.

There are several icon sets which also require dark mode.

>BTW, that parent directory up button icon, is there any way for you to hook that (comctl32.dll) to change it?
Or possibly just tell it to load a different icon?

Sorry but I don't want to make many changes to upstream code.

**Comment by WildByDesign** [comment]
> Sorry but I don't want to make many changes to upstream code.

That’s understandable. I appreciate the work that you are doing here to bring dark mode to 7-Zip.

**Comment by WildByDesign** [comment]
> Currently, the Move icon is not the same in both views of the toolbar. Why? If you asked me which icon would look better, I would say the folder icon with the arrow.

I think what happened at the time was I just wasn't 100% sure which Move icon I preferred and then I ended up forgetting about. I prefer the folder icon with the arrow as well. I'll have to update the icons soon.



> 1. What program did you use to create BMP files with transparency?

I used Inkscape to put together various parts of different SVG files and exported to PNG. The actual BMP transparency had to be done with an antiique/ancient software called Pixelformer (https://www.qualibyte.com/pixelformer/) which is free. None of the more modern programs seemed to handle BMP transparency properly. I used GIMP to copy/paste the PNG into Pixelformer and saved to BMP with transparency.



> 2\. Can you share the comctl32.dll file?

Sure, of course. The images in comctl32 are so limited unfortunately.

[comctl32.zip](https://github.com/user-attachments/files/23565598/comctl32.zip)

**Comment by Dhyfer1** [comment]
> I used Inkscape to put together various parts of different SVG files and exported to PNG. The actual BMP transparency had to be done with an antiique/ancient software called Pixelformer (https://www.qualibyte.com/pixelformer/) which is free. None of the more modern programs seemed to handle BMP transparency properly. I used GIMP to copy/paste the PNG into Pixelformer and saved to BMP with transparency.

Thanks for the link, I'll have to learn how to use that program. So you use Inkscape to work with SVG files, and you export them to PNG, then you use GIMP to copy/paste those files into Pixelformer, and lastly, do you use Pixelformer to save them as transparent BMP files? That's a lot of work, isn't it? 😅

> Sure, of course. The images in comctl32 are so limited unfortunately. [comctl32.zip](https://github.com/user-attachments/files/23565598/comctl32.zip)

Thank you. I also use Windhawk with the Resource Redirection mod, and although the icons in the taskbar did change to your custom icons, the "One Level Up" icon isn't changing. 😭

Within the settings of the Redirect Resources mod, in the Theme Paths section, I entered the full path to the .ini file: `C:\Users\MyUsername\Downloads\Compressed\7-Zip\theme.ini`. This is the content of the .ini file:

```ini
[Redirections] 
C:\ProgramFiles\7-Zip\7zFM.exe=7zFM.exe=
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_*\comctl32.dll=comctl32.dll
```

I don't have anything else configured in the mod settings, just that.

**Comment by Dhyfer1** [comment]
> Yeah. That's part of the reason why I haven't gone back and fixed that one icon. 

So, you are going to update it as you said before? 

> The one thing that is likely missing is that the option within Resource Redirect called `Redirect all loaded resources (experimental)` needs to be checked for redirecting older BMP resources.

Thank you. After enabling that option, the new icon is now displayed.

**Comment by Dhyfer1** [comment]
So I changed the Move icon, but it doesn't look right. This is how it appears in Resource Hacker and 7Zip.

<img width="687" height="365" alt="Image" src="https://github.com/user-attachments/assets/17224742-bc3b-4797-af0e-af93dab16f83" />

<img width="391" height="141" alt="Image" src="https://github.com/user-attachments/assets/433f50dc-b340-41d6-aa6c-44e3c7e870b2" />

**Comment by WildByDesign** [comment]
BMP format in general is not great for DPI scaling either.

I got the process down properly now. I had to import the PNG (that was exported from SVG in Inkscape) into Pixelformer, copy/paste the layer into another Pixelformer window to then export as BMP format.

Here is the fixed/current version: 

[Windows 11 (win32-darkmode).zip](https://github.com/user-attachments/files/23628616/Windows.11.win32-darkmode.zip)

By the way, I may or may not redo all of the icons someday. The issue really is the fact that there are a lot of manual steps that I can't script automatically and therefore time consuming. And, of course, working with 20+ year old file formats is "icky". However, if I do ever get that kind of energy to jump into that whole mess again, I also consider the comctl32 stuff again as well. I just don't want to make any promises because it's just not fun.

I do continue to use 7-Zip though as I always have. And thanks to @ozone10 for making 7-Zip more modern looking/feeling with the whole win32-darkmode subclassing efforts. In my opinion, I prefer this over alternatives like NanaZip which are using XAML Islands and things like that.

**Comment by WildByDesign** [comment]
> I see you didn't mention Gimp here. Do you not need it anymore?

You are right, it's not needed. I made a mistake when I suggested that. I hadn't done the transparent BMP stuff for almost two years so I completely forgot the flow of it.



> But it only worked when I didn't add a background color behind the icon. When is the background color added? When it's still an SVG, PNG, or BMP file? Because when I added a background color, the background color also appeared with the icon, as in the screenshot I showed you of the icon in 7zip in my previous message.

If you are just going for transparency, then no background color is needed. That weird grey background just shows up in File Explorer since it doesn't support it properly. It showed the grey background in that one icon that I updated (when you tried to replace in resource hacker) because I messed up the icon.

**Comment by WildByDesign** [comment]
Here is a screenshot of the latest with the line fix for the new Extract icon and transparent arrow. I will still likely tweak the icons a bit more and will attach the latest icons here later tonight or tomorrow.

This is with Blur Behind.

<img width="491" height="199" alt="Image" src="https://github.com/user-attachments/assets/c9869007-9319-4c56-95b6-b2afe0592d34" />

And here is the small set with Mica Alt (Tabbed)

<img width="498" height="189" alt="Image" src="https://github.com/user-attachments/assets/fb1d5afa-6ae0-4c78-991e-21cebf88eb9b" />

**Comment by WildByDesign** [comment]
Here are the latest: 

[Windows 11 (win32-darkmode).zip](https://github.com/user-attachments/files/23664193/Windows.11.win32-darkmode.zip)

**Comment by Dhyfer1** [comment]
> If you are just going for transparency, then no background color is needed. That weird grey background just shows up in File Explorer since it doesn't support it properly. It showed the grey background in that one icon that I updated (when you tried to replace in resource hacker) because I messed up the icon.

If so, then why did you add gray color to the bmp files? The original bmp files from 7zip have 4-bits depth and appear with a pink background.

<img width="976" height="323" alt="Image" src="https://github.com/user-attachments/assets/75266e3e-9241-46ec-97a2-24eb7faacf57" />

Your bmp files have 32-bit depth and appear with a gray background.

<img width="976" height="323" alt="Image" src="https://github.com/user-attachments/assets/be7bc796-855c-48cf-97da-446eaba40822" />

I have seen many BMP files with different background colors: pink, cyan, black, gray, etc. I still don't understand how you made the gray color in your files show transparency. I wanted to try the whole process from the beginning, but this time a little differently. In Inkscape, I drew a 48x36 rectangle filled with the same background color as your BMP files. `#505050`, then I added this image <img width="48" height="36" alt="Image" src="https://github.com/user-attachments/assets/9e4d6fc9-ee3e-48ee-9c4f-12a8df6761b7" /> on the rectangle and export the image to png, here is the final png<img width="48" height="36" alt="Image" src="https://github.com/user-attachments/assets/3474f2f7-a6d9-494a-b082-f64fe41ca3ce" />

Then I imported the final PNG into Pixelformer and wanted to do what you said before: _I got the process down properly now. I had to import the PNG (that was exported from SVG in Inkscape) into Pixelformer, <ins>copy/paste the layer into another Pixelformer window to then export as BMP format.</ins>_

So in Pixelformer, I select the entire image, copy everything, open a new Pixelformer window, then click File>New. (I leave the default options in the New project :: New image window, and click OK) and then click Edit>Paste. And now what do I do here in this second window to make the gray color transparent? I feel like there's something else to do here.

<img width="933" height="700" alt="Image" src="https://github.com/user-attachments/assets/3fc54456-00e1-4bac-bdb3-d4d61decb6ab" />

Then export the image to 32 bits without changing anything else in this window.

<img width="252" height="138" alt="Image" src="https://github.com/user-attachments/assets/86ab52d1-949d-48c1-b9a2-f73c849c8701" />

But in the end, both in Resource Hacker and in 7zip, the gray background is visible, as you saw in a previous message. What else should I do in the second Pixelformer window?

And thank you for the advice on how to handle SVG files.

**Comment by WildByDesign** [comment]
> If so, then why did you add gray color to the bmp files? The original bmp files from 7zip have 4-bits depth and appear with a pink background.

I don’t actually add the gray color. The png layers that I import into Pixelformer already have a transparent background. I assume that when I export it with Pixelformer that it must be adding the gray background on its own.

However that gray background is only visible in file explorer since it doesn’t support transparent BMP properly.

For example, if I load those final exported bmp images back into Pixelformer, they still show completely transparent background. Same with resource hacker.

From my understanding, programs that support transparent bmp will take the color from the top left pixel and use that color to remove that same color from the entire image background. That is what happens with the pink from the 7-Zip icons as well.

But clearly there is a lot more to it that I don’t understand at all.

Anyway, I don’t think you need to specifically add color to the background. Keep it transparent. I assume Pixelformer makes it gray on export.

**Comment by Dhyfer1** [comment]
> Now you can technically choose Export and export your BMP right from there without copying it. The reason why I do that is because I've got BMP file templates already ready to go with the right file names and file sizes just to make it a bit easier. But you don't have to do that. You could just export from there.

That's what I did too. After importing the png into Pixelformer, I just exported it to bmp, and in the end the bmp appears with a white background. Now, when I copy the image and open a new Pixelformer window, I click on the new file icon and paste the image, which appears as Layer 2. As I said before, depending on how I order the layers (layer 2 above layer 1 or layer 1 above layer 2) and merge them, the final BMP appears with a white or black background. In the image, you can see the SVG file, along with a 48x36 PNG, and the BMPs with white and black backgrounds. Both BMP files appear correctly in Resource Hacker and 7zip.

<img width="536" height="157" alt="Image" src="https://github.com/user-attachments/assets/0648b96e-58a5-40b1-b4c0-6b964905cbbf" />

If you want, you can check it with this png file. 

<img width="48" height="36" alt="Image" src="https://github.com/user-attachments/assets/66c3a6b4-a29d-4503-b757-b5411f210de2" />

Now I think I understand why your BMP files appear with a gray background. I guess it's because you use templates.

> **Question:** If you import one of your final BMPs back into Pixelformer, does the background still show as transparent? Or are you seeing some background color?

Outside of Pixelformer, it appears with a white or black background, as you have already seen. Inside Pixelformer, it appears transparent.

**Comment by Dhyfer1** [comment]
> By the way, I'll attach one of my PNGs here to see if you get the gray background like I do:
> 
> <img alt="Image" width="48" height="36" src="https://private-user-images.githubusercontent.com/26308319/518598158-610df268-3fbf-461b-9e2d-16f062de9bda.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQxMjMzMDcsIm5iZiI6MTc2NDEyMzAwNywicGF0aCI6Ii8yNjMwODMxOS81MTg1OTgxNTgtNjEwZGYyNjgtM2ZiZi00NjFiLTllMmQtMTZmMDYyZGU5YmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTI2VDAyMTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZjZkODE0OTk0YzM3NDJiNGEyOTliMjQzMzRlOWE0YWJlZDE1NmEyMmM4MjJmNTQ2MGQ0MmY4MGFiODZlYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H7wizwIVkEZNGW5-fRj1hzmAjxo6XIhdFQoFqnG7sPg">

Hmm After exporting your PNG file to BMP, the background appears gray. 

<img width="649" height="187" alt="Image" src="https://github.com/user-attachments/assets/a85d8336-29b2-42d3-ba52-c340040a4c29" />

Now I'm starting to think that the gray background doesn't come directly from Pixelformer, but from what you did with the SVG file in Inkscape before exporting it to PNG. I guess you used layers or templates when editing the icons in Inkscape, and when the icon was ready, you exported it to PNG and then to BMP, and it ended up with that gray background color.

This is my SVG file; try it and see if you get a gray background when it's converted to BMP. In my case, I get a white background.

![Image](https://github.com/user-attachments/assets/e3a933ea-17f6-4eec-977f-bc7bff85d271)

> Anyway, I think that we should not worry about what it looks like in File Explorer since it doesn't have proper support for it. What matters most is that the applications like 7-Zip and Resource Hacker show it properly. I don't think we have much (if any) control over the background color that shows in Explorer.

When I asked you about how to add background color to a BMP file and keep that color transparent, I wasn't referring to the bmp file looking good in the file explorer, that's not important. What I meant was that, for example, the original 7zip bmp files have a pink background. And I thought that if I wanted to edit 7zip bmp files, the background of the new custom bmp files should also be the same color like the original files, so that the program wouldn't have problems displaying the new icons. But after seeing that your files have a gray background, they also appear correctly in 7zip even though their background is not the same color as the original files, which leads me to believe that the background color doesn't matter for a transparent bmp. It works in 7zip at least; I haven't tried it yet in IDM, which has a toolbar that uses bmp files and its background color is gray.

By the way, I've already figured out what to do to make bmp files have a background color while still being transparent.  Before exporting to PNG, I clicked where the arrow is pointing, which opens the "Background Color" window. 

<img width="1366" height="720" alt="Image" src="https://github.com/user-attachments/assets/017dad84-9c62-427c-bf2e-7eb27cc87e47" />

There I select the background color before exporting to PNG. The background color will not appear in the final PNG, but it will appear in the BMP file. You can try it with this new png file that already has the blue background color, just export it to bmp and you'll see it appears with a blue background and it displays correctly in 7zip and Resource Hacker 

<img width="48" height="36" alt="Image" src="https://github.com/user-attachments/assets/95d6efab-538b-4201-b78f-e8748867620c" />

**Comment by ozone10** [comment]
Icons are updated
