### ISSUE TITLE
Do you mind adjusting the color of the grid line and make it lighter, the color is too bright now?

### ISSUE THREAD

**Issue by mofazhe** [ozone10/7zip-Dark7zip#5]
![image](https://github.com/user-attachments/assets/eef3c2d2-315f-4e59-898c-862aa83d44b3)

**Comment by ozone10** [comment]
@mofazhe 
there was already commit https://github.com/ozone10/7zip-Dark7zip/commit/f1c57717a6a86722c76c708c0a4c76f0b7e4e286 from yesterday but with no release. I needed some time to test it.

But release [v0.4.3.0](https://github.com/ozone10/7zip-Dark7zip/releases/tag/v0.4.3.0) should fulfill your request. 
![image](https://github.com/user-attachments/assets/dc1a89ae-7dd9-4dc2-aa6d-ace2ee00a362)
