### ISSUE TITLE
7zip is not responding

### ISSUE THREAD

**Issue by mofazhe** [ozone10/7zip-Dark7zip#7]
Going back up several times until this path, 7zip appears unresponsive. I tried the official version, it works well.
Version: v24.08-v0.4.3.0
![image](https://github.com/user-attachments/assets/2782dfe4-d00e-4d7c-9399-7aeb6f668c06)

**Comment by ozone10** [comment]
There is some issue in code for vertical gridlines. Unfortunately I don't have time to properly investigate it.
But https://github.com/ozone10/7zip-Dark7zip/releases/tag/v24.08-v0.4.3.1 should fix this issue.
I will close this for now, if there is still issue I will reopened it.

**Comment by CennoxX** [comment]
For me v0.4.3.1 fixes the issue.
