### ISSUE TITLE
Google Chrome flagging the files as "dangerous downloads"

### ISSUE THREAD

**Issue by Wisdawn** [ozone10/7zip-Dark7zip#9]
On my end at the time of this post, Google Chrome is flagging both releases as "dangerous downloads" and by default blocking them from being downloaded. This almost never happened to me before on Github, and rarely happens generally speaking, so I had to post about it.

Why would Google Chrome detect such a thing?

**Comment by ozone10** [comment]
@Wisdawn
this is false positive.
Check #8
